# Generated by Django 5.2 on 2025-06-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platesession',
            name='amount_due',
        ),
        migrations.RemoveField(
            model_name='platesession',
            name='paid',
        ),
        migrations.AddField(
            model_name='platesession',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='platesession',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platesession',
            name='entry_time',
            field=models.DateTimeField(),
        ),
    ]
