# Generated by Django 5.2 on 2025-06-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_platesession_amount_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platesession',
            name='charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platesession',
            name='total_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
