# Generated by Django 5.2 on 2025-06-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_platesession_charge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platesession',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='platesession',
            name='total_time',
        ),
    ]
