# Generated by Django 5.2 on 2025-06-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_platesession_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platesession',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
