# Generated by Django 5.2 on 2025-06-18 04:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_platesession_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platesession',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
