# Generated by Django 5.2 on 2025-06-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_platesession_entry_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Bus', 'Bus')], max_length=10, unique=True)),
                ('total_slots', models.IntegerField(default=0)),
                ('occupied_slots', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='platesession',
            name='charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='platesession',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platesession',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Bus', 'Bus')], default='Car', max_length=10),
        ),
    ]
