# Generated by Django 5.2 on 2025-06-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_vehicleslot_platesession_charge_platesession_is_paid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleSlot',
        ),
        migrations.AlterField(
            model_name='platesession',
            name='charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platesession',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Bus', 'Bus')], max_length=10),
        ),
    ]
