# Generated by Django 5.2 on 2025-06-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_employeeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(default='Staff', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
    ]
